<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dc9kfp5gt/image/upload/v1554307276/IMG_20180227_214951_697_o3buej_rstc5c.jpg" alt="Mark Essien">
                        <h6>Ogundiji Bolade</h6>
                        <p>Backend Software Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/bollybkampo" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/adroit11" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@ogundijiboladeadio" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>
                            An Adroit, Driven, Goal oriented Web developer focused on solving web problems.
                            I code in JavaScript and PHP. 
                            I am very passionate about learning new skills, technology and frameworks.
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | NODE</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
