<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/azmotech/image/upload/v1554329488/azmotech.png" alt="Moses Aizee">
                        <h6>Moses Aizee</h6>
                        <p>Front-End Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/eyezee07" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/azmomaisontech" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@askofnolongtin" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am Moses Aizee, a graduate of Mathematics and Computer Science from the University of Portharcourt. 
                         I am passionate about problem-solving and contributing my little quota for the advancement of technology.
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | React | Nodejs</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
