<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/blessed/image/upload/v1554317424/blessed.jpg" alt="Mark Essien">
                        <h6>Blessed Yahaya</h6>
                        <p>Full Stack Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/yahayablessed" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/makarios1214" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a passionate software developer, and a recent graduate of Computer Engineering from the University of Benin. I am focused on building web products that solve local and global challenges. I am very enthusiastic about learning new skills, technology and frameworks, </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | NodeJS | ReactJS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
