<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/daemoniic/image/upload/v1554325700/96699dfe-970e-44fb-8171-814eccc849f0.jpg" alt="Mark Essien">
                        <h6>Igunnu Emmanuel</h6>
                        <p>Backend intern</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/js_Genin" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Daemonicc" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@igunnuemmanuel" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am Igunnu Emmanuel Boluwastife, I am final Year student of Computer Engineering, University Of Benin. I joined the hotel.ng internship to gain probelm solving skill and also to have improving my coding skill and collaborate with other developers. I have a year experience in coding using the MERN stack.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | MongoDB </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
