<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dvscfg5kr/image/upload/v1554312725/1ab20190-19d4-4334-8cf5-e4e174205b72.png" alt="Desmond Ngwuta">
                        <h6>Desmond Ngwuta</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="http://twitter.com/chydeebere" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="http://github.com/chydee" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="http://medium.com/chydi" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a Front-end Developer, my tool is my code, and the product is the masterpiece. I build scalable web apps for my clients. I am the Balogun of Wordpress!</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PostgreSQL | NodeJs</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
