<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/mystique/image/upload/v1554325780/hng/5.jpg" alt="Okafor Samuel">
                        <h6>Okafor Samuel</h6>
                        <p>Full Stack Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/SwizzSamuel16" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/SwizzSamuel" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am an aspiring full stack developer based in Lagos.I use the JavaScript language to build stuffs that would work on a computer.I am also very keen in the field of data science with the use of the Python language!.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | React | Node</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
