<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/deiaeqbyy/image/upload/v1554313473/hng2.jpg" alt="Paul Opeyemi">
                        <h6>Asalu Paul Opeyemi</h6>
                        <p>Fullstack WebDeveloper</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/CuriousPaul2" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/CuriousPaul01" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hey i'm Paul and i'm a major IT/Tech enthusiast, a student (i'm currently running a five year Bsc program in Computer Engineering at the University of Lagos, Nigeria). Also i love Sponge bob</p>
                        <br/>
                        <h6>Skills</h6>
                        <p>JavaScript | CSS| Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
