<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/edlac-algorithm/image/upload/v1554309609/dboy.jpg" alt="Oladipo Abiodun .D">
                        <h6>Oladipo Abiodun Dauda</h6>
                        <p>Backend Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Daudont" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Daudongit" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@daudonmail" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I'm a web developer with five year experience in Php and Javascript, I also have passion for mobile application development, computer networking and its applications. I love fictional movies and local food</p>
                        <br />
                        <h6>Skills</h6>
                        <p>PHP | JavaScript | Tcp/Ip</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
