<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dejiabiola/image/upload/v1554316830/deji_abiola.png" alt="Deji Abiola">
                        <h6>Adedeji Abiola</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="twitter.com/deji_abiola" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="github.com/deji_abiola" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="medium.com/@deji_abiola" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Self taught front-end engineer and UI/UX developer. Entusiastic about creating responsive and interactive web applications. Game of thrones addict.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | React | Nodejs</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
