<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dzf7vwbp9/image/upload/v1554317705/emmyyusufu_b6nygs.png" alt="Emmanuel Yusufu">
                        <h6>Emmanuel Yusufu</h6>
                        <p>Aspiring Product designer & Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/emmyyusufu" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/emmyyusufu" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@emmyyusufu" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi! I am a bdding Product Designer and Developer. I am passionate about creating digital products with great user experiences, simple elegance and functionality. Asides all these I enjoy reading, larning and contributing to real world projects.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | UI/UX | MERN stack</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>