<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/djksghat4/image/upload/v1554327011/CROPED_PHOTO.jpg" alt="Aigbiluese Eronmonsele">
                        <h6>Aigbiluese Eronmonsele</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://www.twitter.com/erons_xo" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://www.github.com/eronmmer" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://www.medium.com/@eronmmer" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I'm Aigbiluese Eronmonsele. I'm a Computer Science student and a Front-end Developer. I love writing code, sharing my knowledge with people and solving challenges. I'm comfortable using CSS and JavaScript to build nice user interfaces and web applications.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>CSS | JavaScript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
