<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/franklinanozie/image/upload/v1554324645/franklinanozie.jpg" alt="Anozie Franklin Chidiebere">
                        <h6>Anozie Franklin Chidiebere</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/franklinanozie" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/BoboFrank" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>My name is Anozie Franklin Chidiebere, a front-end web developer, Artificial Intelligence (AI), Virtual Reality (VR) and Machine Learning (ML) enthusiast. I have been developing myself for a career in web development for the past one year mostly through self-taught means. Currently I’m on track for an internship with Hotels.ng.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | React | HTML</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
