<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/iamserver/image/upload/v1554307449/52634582_2089927074448870_4475630426676789248_n_suucdv.jpg" alt="Egbeyemi Oladayo">
                        <h6>Egbeyemi Oladayo</h6>
                        <p>Backend Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/iamserverr" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/DateTech" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@iamserverr target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a student freelancer developer always craving to learn more technologies. A lover of good music, a keyboardist and drummer. A kingdom worker</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>