<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dtuoge1pg/image/upload/v1554323121/profile-pics-ikenna.jpg" alt="Onyejiaka Samuel Ikenna">
                        <h6>Onyejiaka Samuel Ikenna</h6>
                        <p>Back-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/OnyejiakaS" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/izuoba" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@onyejiaka.ikenn" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A young passionate programmer, ready to dive into new areas in web and mobile app development. 
						Worked with various company across different verticals. I am looking to grow in my career as 
						programmer and be part of solutions to some of the challenges facing our world. </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | MySQL</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
