<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/bitmillex-ltd/image/upload/v1554311601/b3dd00d9-b979-4e1a-8b8b-a87ac0c58a4c.jpg" alt="Jendy jasper">
                        <h6>Chijindu Iwuchukwu</h6>
                        <p>Project Manager</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Jendy36" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/JendyJasper" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@iwuchukwuchijindu" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a computer scientist based in 
                        Owerri, Imo state. I have a great passion for anything technonoly and how it affects
                         our ecosystem. I have been part of some projects that will be launching very soon,
                          two of which includes a blockchain based project and a telemedicine project, which I
                           was the project managers</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Python |Project Management | Pen Testing</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
