<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dfktmw0ar/image/upload/v1554321032/092f96b6-6bb8-41d0-8b5c-bd0bc598f887.jpg" alt="Yusu Khadijat">
                        <h6>Yusuf Khadijat</h6>
                        <p>Full stack developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Yusufkjart" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/kjart" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@khadijatyusuf" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Programming is what i love to do. i code in PHP, JavaScript, NodeJs and other javascript libraries. I also love to read at my free time and watch movies. I am open to learning anything new.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | Node.js</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
