<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/thevetdoctor/image/upload/v1554313024/oba.jpg" alt="Obafemi Oderanti">
                        <h6>Obafemi Oderanti</h6>
                        <p>Intermediate FullStack Developer</p>
                        <ul class="list">
                           <li><a href="https://www.twitter.com/animalworldng" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://www.github.com/thevetdoctor" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://www.medium.com/@animalworldng" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A passionate software solutions provider, team player and desirous to change the technology landscape of Africa one line of code at a time</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Python | PHP</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>