<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/pheeque/image/upload/v1554311246/IMAG0219.jpg" alt="Rafik Abdulwahab">
                        <h6>Rafik Abdulwahab</h6>
                        <p>Full Stack Developer</p>
                        <ul class="list">
                           <li><a href="//twitter.com/pheeque" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="//github.com/pheeque" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="//dev.to/pheeque" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>
                           Freelance full stack developer interested in how teams build software.
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | C++</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
