<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/sarscode/image/upload/v1554309585/sarscode.png" alt="Salifu Sani Rich">
                        <h6>Salifu Sani Rich</h6>
                        <p>Frontend Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/sarscode" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/sarscode" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@sarscode" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I identify problems and solve them with code. I have a keen interest in Web Technology and Open Source. I am passionate about creating awesome interfaces for the web and improving user experience and performance across web apps.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript & NodeJs | SCSS & CSS | HTML</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
