<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
<?php include 'partials/header.php'; ?>

<body class=" pi">
  <?php include 'partials/navbar.php'; ?>
  <section class="main-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-6 col-xs-12">
          <div class="col-md-6 col-xs-12">
            <div class="intern-block border-blue">
              <img src="https://res.cloudinary.com/alphex-code-ltd/image/upload/v1554317230/edit_profile_2.jpg" alt="Timilehin Olumofin">
              <h6>Timilehin Olumofin</h6>
              <p>Full-stack Developer</p>
              <ul class="list">
                <li><a href="https://twitter.com/therealprofT" target="_blank" <i class="fab fa-twitter fa-2x"></i></a></li>
                <li><a href="https://github/timzprof" target="_blank" <i class="fab fa-github fa-2x"></i></a></li>
                <li><a href="https://medium.com/@timilehin.olumofin" target="_blank" <i class="fab fa-medium fa-2x"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-6 col-xs-12 align-items-center">
            <div class="intern-bio border-blue">
              <h6>About me</h6>
              <p>I'm a music and game lover to the core.</p>
              <p><b>Education</b>: Undergoing B.SC Program for Computer Science</p>
              <p><b>Work</b>: I freelance as a Full-Stack Web Developer</p>
              <br />
              <h6>Skills</h6>
              <p>JavaScript | PHP</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>
</body>
<?php include 'partials/footer.php'; ?>

</html>