<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/tomesyy/image/upload/v1554318448/hng/IMG_20181221_090931_8.jpg" alt="Mark Essien">
                        <h6>Adesanya Adetomiwa</h6>
                        <p>Software Engineer</p>
                        <ul class="list">
                           <li><a href="twitter.com/AdesanyaTomiwa2" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="github.com/tomesyy" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="medium.com/@adesanyaadetomiwa01" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am Tomiwa, an aspiring Software Engineer based in Lagos, Nigeria.
                        I learn and use javscript everyday to build stuff that work on the computer and I would also love to delve into machine learning or data science sooner. I just love everything technology!</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Node | React</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
